name: mace
channels:
  - https://ftp.osuosl.org/pub/open-ce/1.7.2
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - openblas
  - pytorch=1.12.1=cuda11.4_py39_1
  - pillow
  - pyarrow
  - pip
  - pip:
      - mlflow
      - --editable .
